### ISSUE TITLE
Problem with the searchengines module

### ISSUE THREAD

**Issue by MadeByGabe** [eecolella/GoToAnchor#1]
```
reloading plugin GoToAnchor.go_to_anchor
Traceback (most recent call last):
  File "D:\Programs\Sublime Text Build 3047 x64\sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "D:\Programs\Sublime Text Build 3047 x64\sublime_plugin.py", line 671, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "go_to_anchor in D:\Programs\Sublime Text Build 3047 x64\Data\Installed Packages\GoToAnchor.sublime-package", line 25, in <module>
ImportError: No module named 'searchengines'
```

**Comment by jcoc611** [comment]
This fixes issue #1.
